### ISSUE TITLE
朴素树状数组i

### ISSUE THREAD

**Issue by chronicle12345** [Heartfirey/ACM_Algorithm_Library#1]
2-数据结构那节
4.树状数组
朴素树状数组
中有以下代码
`int kth(int i){
        int cnt = 0, ret = 0;
        for(int i = log2(len); ~i; --i){
            ret += 1 << i;
            (ret >= len || cnt + tree[ret] >= i) ? (ret -= 1 << i) : (cnt += tree[ret]);
        }
        return ret + 1;
    }
`
会不会写错了（传值i，并且循环又定义i）？

**Comment by Heartfirey** [comment]
Thank you for telling me about this issue, it has been resolved in [0d9fa31](https://github.com/Heartfirey/ACM_Algorithm_Library/commit/0d9fa31ec0f0d62df3777ed06c3e92de99e0e150)
