### ISSUE TITLE
2.数据结构勘误

### ISSUE THREAD

**Issue by chronicle12345** [Heartfirey/ACM_Algorithm_Library#3]
![OL7JW3P(9KZTK4MOMK I}00](https://github.com/Heartfirey/ACM_Algorithm_Library/assets/93925665/6ad2d562-7437-4b10-9525-2b946a3f6a0e)
此处应该为lc[qr]

**Comment by chronicle12345** [comment]
主席树维护静态区间第k大的那里

**Comment by Heartfirey** [comment]
Thank you for your correction, this bug has been fixed in [Fix](https://github.com/Heartfirey/ACM_Algorithm_Library/commit/a8b4ceddf5891defc78e7d3d3eed11ac7b56662a)

**Comment by Heartfirey** [comment]
Thank you for your correction, this bug has been fixed in [Fix](https://github.com/Heartfirey/ACM_Algorithm_Library/commit/a8b4ceddf5891defc78e7d3d3eed11ac7b56662a)
